Add mocked client + subclass of XCTestCase
qutheory/vapor pull request #2928
Opened 2022-12-27 18:46 UTC by Kithin

I have created a spy client, in order to the stub the response and being able to verify the request.

I also created a XCTestVaporTestCase, to reduce boilerplate code. You don't need to configure the application every time.

You just simple do this:

```
final class ExampleTests: XCTestVaporTestCase {
     func test_example() throws {
           try client.stubResponse(httpStatus: .ok)
     }
}
```

2022-12-30 18:34 UTC, 0xTim requested changes
Initial comments - it would also be good to add this to a test to a) make sure it works and b) show how to use it

2022-12-30 18:34 UTC, 0xTim commented on Sources/XCTVapor/XCTVaporTestCase.swift
> +import XCTest
Let's remove this - we can just add how to use in the docs since most people using it will want to customise it

2022-12-30 18:34 UTC, 0xTim commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +    private var stubResponse: ClientResponse!
Let's default to an empty 200 OK instead of using an IUO

2022-12-30 18:34 UTC, 0xTim commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +        self.requestUrlComponentsUsed.scheme = request.url.scheme
We should definitely store the requests directly in to an array

2022-12-30 18:34 UTC, 0xTim commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +public final class SpyClient: Client {
We're likely definitely missing an import on Foundation here

2022-12-30 18:34 UTC, 0xTim commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +    private(set) var requestUrlComponentsUsed: URLComponents = .init()
I'd like to avoid URLComponents if possible, I don't see any issue just storing the request directly

2022-12-31 09:59 UTC, Kithin commented on Sources/XCTVapor/XCTVaporTestCase.swift
> +import XCTest
Just curious, for understanding and learning, why do we want to remove this import XCTest?

2022-12-31 10:03 UTC, Kithin commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +        self.requestUrlComponentsUsed.scheme = request.url.scheme
Why do we want to store the request in an array? 

Is it because in case there are multiple request being made. And with an array you know how many request in total was made. And also being able to select a specific request (e.g. the third request).

Is this the reason?

2022-12-31 10:03 UTC, Kithin commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +public final class SpyClient: Client {
Good one. I will add this import

2022-12-31 10:11 UTC, Kithin commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +    private(set) var requestUrlComponentsUsed: URLComponents = .init()
The reason why I decided to use URLComponents was because in situations where there is also a query. With: `request.url.query`, you get back a String. And the problem with it, is that the order of key, value pairs are random.
Meaning the first time you get it like this: `key_1=value_1&key_2=value_2`
and the second time maybe like this: `key_2=value_2&key_1=value_1`
So it becomes impossible to make assertions in your test.

And with: `requestUrlComponentsUsed.query`, you get back an array. So it's easier to make assertions in your tests. By looping over it.

2022-12-31 10:13 UTC, Kithin commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +    private var stubResponse: ClientResponse!
What does IUO mean?

2022-12-31 10:14 UTC, Kithin commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +    private var stubResponse: ClientResponse!
Why do you want to have a default stubResponse of status code 200?

Just curios

2022-12-31 11:17 UTC, Kithin commented
@0xTim can you maybe help me, with this compiling error: 
`Undefined symbol: _$s11Development9configureyy5Vapor11ApplicationCKF`

In the sub class I created: XCTVaporTestCase, I have added this code on line 20: 
`try configure(app)`

After that I got this error:
`Cannot find 'configure' in scope`

That's why I added this import: 
`import Development`

But then I got this symbol error:
`Undefined symbol: _$s11Development9configureyy5Vapor11ApplicationCKF`

2022-12-31 12:29 UTC, 0xTim commented
@Kithin that's because you're trying to use something that links XCTest in an executable which isn't possible. If you use it in a test similar to https://github.com/vapor/vapor/blob/main/Tests/VaporTests/ApplicationTests.swift#L104 (that file is probably a good place for it) it should work

2022-12-31 12:30 UTC, 0xTim commented on Sources/XCTVapor/XCTVaporTestCase.swift
> +import XCTest
Sorry I meant remove the whole file - those using the fake client will likely have much more complicated set ups that make this class redundant

2022-12-31 12:30 UTC, 0xTim commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +    private var stubResponse: ClientResponse!
This avoids it crashing in case they don't set a response and makes it easier to use in tests where they may not actually test the client stuff but still use it to avoid outbound requests in tests

2022-12-31 12:31 UTC, 0xTim commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +        self.requestUrlComponentsUsed.scheme = request.url.scheme
Yep exactly, you might have a route that makes 5 requests and you want to assert the order and contents of each request for example

2022-12-31 12:32 UTC, 0xTim commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +    private(set) var requestUrlComponentsUsed: URLComponents = .init()
There's nothing stopping anyone using it from doing this themselves. This reason I want to about `URLComponents` is that adds a dependency on `FoundationNetworking` which we want to avoid on Linux if possible

2022-12-31 13:00 UTC, Kithin commented
Aaaah, so you mean, I should move this file in the test folder instead of the source folder?

But is it still accessible for people to use in their own tests?

2022-12-31 13:02 UTC, Kithin commented
That something is that the SpyClient I created or because that class is a subclass of XCTestCase, and this super class can only be executed in test?

2023-01-01 01:52 UTC, 0xTim commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +    private var stubResponse: ClientResponse!
(IUO is implicitly unwrapped optional)

2023-01-01 01:53 UTC, 0xTim commented
The `SpyClient` should stay in XCTVapor but where you try to use it should be in a test case

2023-01-01 10:56 UTC, Kithin commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +    private(set) var requestUrlComponentsUsed: URLComponents = .init()
Could you explain, why. Just curious and to learn.

2023-01-01 12:56 UTC, Kithin commented
> @Kithin that's because you're trying to use something that links XCTest in an executable which isn't possible. If you use it in a test similar to https://github.com/vapor/vapor/blob/main/Tests/VaporTests/ApplicationTests.swift#L104 (that file is probably a good place for it) it should work

I have tried it, but then I get the same error as in my previous comment:

```
@0xTim can you maybe help me, with this compiling error:
Undefined symbol: _$s11Development9configureyy5Vapor11ApplicationCKF

In the sub class I created: XCTVaporTestCase, I have added this code on line 20:
try configure(app)

After that I got this error:
Cannot find 'configure' in scope

That's why I added this import:
import Development

But then I got this symbol error:
Undefined symbol: _$s11Development9configureyy5Vapor11ApplicationCKF
```

2023-01-01 12:56 UTC, Kithin commented
> @Kithin that's because you're trying to use something that links XCTest in an executable which isn't possible. If you use it in a test similar to https://github.com/vapor/vapor/blob/main/Tests/VaporTests/ApplicationTests.swift#L104 (that file is probably a good place for it) it should work

I have tried it, but then I get the same error as in my previous comment:

```
@0xTim can you maybe help me, with this compiling error:
Undefined symbol: _$s11Development9configureyy5Vapor11ApplicationCKF

In the sub class I created: XCTVaporTestCase, I have added this code on line 20:
try configure(app)

After that I got this error:
Cannot find 'configure' in scope

That's why I added this import:
import Development

But then I got this symbol error:
Undefined symbol: _$s11Development9configureyy5Vapor11ApplicationCKF
```

2023-01-04 11:22 UTC, 0xTim commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +    private(set) var requestUrlComponentsUsed: URLComponents = .init()
FoundationNetworking means that you need curl which isn't available by default on many systems and can cause issues with linking. So we avoid using it. This also ties nicely in with the upcoming Foundation changes to split things up and best practices for us to make our library as small as possible

2023-01-08 20:26 UTC, Kithin commented
> Can you push the current test case up?

@0xTim I have pushed it. It's the latest commit: UPDATE - set mocked client

2023-01-11 15:14 UTC, 0xTim commented on Tests/VaporTests/ApplicationTests.swift
> +        try configure(app)
The tests are currently failing because this function doesn't exist - you can just remove this line for the tests
```suggestion
        
```

2023-01-11 19:25 UTC, Kithin commented on Tests/VaporTests/ApplicationTests.swift
> +        try configure(app)
Does this not mean the mocked client will not be used by the application?

2023-01-11 19:26 UTC, familon16 commented
hi


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
01/12/23,
12:56:50 AM

On Thu, Jan 12, 2023 at 12:56 AM Kithin ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In Tests/VaporTests/ApplicationTests.swift
> <https://github.com/vapor/vapor/pull/2928#discussion_r1067377935>:
>
> > +
> +        try configure(app)
>
> Does this not mean the mocked client will not be used by the application?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vapor/vapor/pull/2928#discussion_r1067377935>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF5PHC55Q3IEWKZIXCEEPYLWR4CMVANCNFSM6AAAAAATKUPN7Q>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-01-12 18:59 UTC, Kithin commented on Tests/VaporTests/ApplicationTests.swift
> +        try configure(app)
I have removed the line of code, thank you for your help

2023-01-15 20:20 UTC, Kithin commented
@0xTim the test keeps failing on GitHub actions, but not locally. Can you perhaps help me?

2023-01-16 14:28 UTC, 0xTim commented
@Kithin you're using the new generics syntax from Swift 5.7 that isn't available on older Swift versions. You'll need to find a work around

2023-01-16 14:30 UTC, 0xTim commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +    private var stubResponse: ClientResponse = .init(status: .ok)
This should be public to make it completely customisable

2023-01-17 20:24 UTC, Kithin commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +    private var stubResponse: ClientResponse = .init(status: .ok)
Do you mean stubResponse?

Is the stubResponse() method not enough? 

Could you explain, trying to learn geen your thoughts.

2023-01-18 10:58 UTC, 0xTim commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +    private var stubResponse: ClientResponse = .init(status: .ok)
Yeah `stubResponse`. The function is good for most people to allow them to set most common cases but it's impossible to predict what people might want to try and test (custom headers, missing bodies, empty bodies etc) so we should let them set the response wholesale if needs be

2023-01-26 05:20 UTC, Kithin commented
@0xTim do you have more feedback. And I also wanted to thank you for your help, when I was stuck.

2023-02-23 17:55 UTC, 0xTim requested changes
Sorry for the delay - last few changes and I think we're good to go!

2023-02-23 17:55 UTC, 0xTim commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +    private(set) var requestsUsed: [ClientRequest] = []
```suggestion
    private(set) var requestsSeen: [ClientRequest] = []
```

2023-02-23 17:55 UTC, 0xTim commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +        self.requestsUsed.append(request)
```suggestion
        self.requestsSeen.append(request)
```

2023-02-23 17:55 UTC, 0xTim commented on Sources/XCTVapor/TestDoubles/Spies/SpyClient.swift
> +import Foundation
```suggestion
import Foundation
import Vapor
import NIOCore
```

2023-02-26 20:35 UTC, Kithin commented
@0xTim When I merge main into this feature branch, I don't get that merge conflict. But I have fixed the merge conflicts anyway. But the PR I still get the message: This branch has conflicts that must be resolved

2023-02-26 21:19 UTC, 0xTim commented
@Kithin It's in the application tests, I can't see the test you added anymore?

2023-02-26 21:25 UTC, Kithin commented
> @Kithin It's in the application tests, I can't see the test you added anymore?

I didn't added a new test, I updated this test: testBoilerplate

2023-02-27 10:40 UTC, 0xTim commented
@Kithin Hmm I see. I can't check the merge conflicts because I don't have access to the fork. So the easiest thing to probably do is close the PR, update your fork, then create a new branch and copy the code across. Let's put the test for the client in its own test case as well

2023-09-05 19:10 UTC, SpaceboatDVLP commented
Would it make sense to add a `configure` function within SpyClient in case someone wants to init a stubbed response within a unit test rather than setting up the client within the XCTestCase? For example:

`static func configure<T: Content>(on app: Application, with response: T) throws {
        let client = SpyClient(eventLoop: app.eventLoopGroup.next())
        app.clients.use { _ in
            return client
        }
        try client.stubResponse(httpStatus: .ok, responseData: response)
    }`
    
Then you could use it within a unit test like this:

`let mockResponse = MockResponse(message: "nice")
    try SpyClient.configure(on: app, with: mockResponse)`

Thanks for this by the way.

2023-09-06 08:45 UTC, 0xTim commented
@SpaceboatDVLP that pattern would be to store the instance of the `SpyClient` on the `XCTestCase`

So in your test case you'd do
```swift
self.spyClient.stubResponse(httpStatus: .ok, responseData: response)
```
That allows you to also inspect the request send to the client etc

There's nothing stopping you adding the configure function in your code of course

2024-03-15 09:56 UTC, AFutureD commented
Support stub to a specific request?

I have a [demo](https://github.com/AFutureD/SignInWithAppleVapor/blob/main/Tests/SignInWithAppleVaporTests/Utils/MockClient.swift)
And an [example](https://github.com/AFutureD/SignInWithAppleVapor/blob/3327be40adc5a0c139c7546b4ebc0abdd934e495/Tests/SignInWithAppleVaporTests/AppleApiTests.swift#L82) to use it.

2024-10-15 23:09 UTC, Naveen-C-Ramachandrappa approved these changes

2026-06-17 08:09 UTC, closed without merging