Use request's identifier as request-id when not set by X-Request-Id
qutheory/vapor pull request #3117
Opened 2023-12-08 17:48 UTC by baarde

### Motivation

The Request's `id` property was added in #2964 to expose the `request-id` identifier used for logging.

#3072 changed this behavior. The `request-id` identifier is now set:
* to the value from the `X-Request-Id` header, when the header is present,
* to a random identifier, when the header is absent.

Having two different identifiers is confusing. So, when the `X-Request-Id` is absent, we should probably use the same value for both identifiers.

### Alternatives considered

#### Using the X-Request-Id header as the Request's `id`.
We could decide that the Request's `id` and the logger's `request-id` should always be the same, and use the `X-Request-Id` header for both. However, the documentation currently states that `id` is *A uniquely generated ID for each request*.

2023-12-08 18:20 UTC, MahdiBM requested changes
Looks good but one comment

2023-12-11 00:51 UTC, 0xTim commented on Sources/Vapor/Request/Request.swift
>              logger[metadataKey: "request-id"] = .string(requestId)
Yes I concur, we should either get the ID from the header and use that or generate one. When we have an ID it should be consistent everywhere

2023-12-11 01:37 UTC, gwynne commented on Sources/Vapor/Request/Request.swift
>              logger[metadataKey: "request-id"] = .string(requestId)
Very much agreed also.

2023-12-11 10:20 UTC, baarde commented on Sources/Vapor/Request/Request.swift
>              logger[metadataKey: "request-id"] = .string(requestId)
Thanks for the suggestions. I've updated the PR.

2023-12-11 18:19 UTC, MahdiBM approved these changes

2023-12-11 18:19 UTC, MahdiBM commented on Sources/Vapor/Request/Request.swift
> +        let requestId = headers[.xRequestId].first ?? UUID().uuidString
Looks fine but i'd prefer `.first(name:)`, will be slightly more performant as it wouldn't be filter/collecting stuff when eventually we do `.first` anyway:
```suggestion
let requestId = headers.first(name: .xRequestId) ?? UUID().uuidString
```

2023-12-12 10:07 UTC, MahdiBM commented
@gwynne @0xTim this is ready IMO. 🙂

2023-12-13 13:04 UTC, 0xTim approved these changes

2023-12-13 13:06 UTC, merged